PYTHON_VERSION="${PYTHON_VERSION:?}"
BUILD_URL="${BUILD_URL:?}"
BUILD_BRANCH="${BUILD_BRANCH:?}"
BUILD_COMMIT="${BUILD_COMMIT:?}"
BUILD_PIPELINE_NAME="${BUILD_PIPELINE_NAME:?}"
CODE_DIR="${CODE_DIR:?}"
SANDBOX_DIR="${SANDBOX_DIR:?}"
PIP_CACHE_DIR="/pip-cache"
VENV_DIR="${SANDBOX_DIR}/venv"
ERR_FEEDBACK_FILE="${SANDBOX_DIR}/error.feedback"

GITHUB_PULL_REQUEST_ID="${GITHUB_PULL_REQUEST_ID:-}"
GITHUB_PULL_REQUEST_BRANCH_NAME="${GITHUB_PULL_REQUEST_BRANCH_NAME:-}"
GITHUB_REPO_NAME="${GITHUB_REPO_NAME:-}"

TG_BOT_TOKEN="${TG_BOT_TOKEN:-}"
TG_CHAT_ID="${TG_CHAT_ID:-}"
TG_API_HOST="${TG_API_HOST:-}"

TEST_NAME_PYTEST="py-${PYTHON_VERSION}-pytest"
TEST_NAME_FLAKE8="py-${PYTHON_VERSION}-flake8"
TEST_NAME_MYPY="py-${PYTHON_VERSION}-mypy"

declare -A TESTS_SYMBOLS
TESTS_SYMBOLS[${TEST_NAME_PYTEST}]="⚙"
TESTS_SYMBOLS[${TEST_NAME_FLAKE8}]="🔔"
TESTS_SYMBOLS[${TEST_NAME_MYPY}]="🤖"
